{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "workload-identity-labeler.serviceAccountName" . }}
  namespace: {{ include "workload-identity-labeler.namespace" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ with .Values.azure.clientId }}
    {{- if eq .Values.azure.authMode "workload-identity"}}
      azure.workload.identity/client-id: {{ . | quote }}
    {{- end }}
    {{- end }}
    {{- range $k, $v := . }}
      {{- $value := $v | quote }}
      {{- printf "%s: %s" (tpl $k $) (tpl $value $) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "workload-identity-labeler.labels" . | nindent 4  }}
    {{- with .Values.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}